import type { CalculatorManifest } from "@/features/clinical-calculators/types";

const yesNoOptions = [
  { label: "Selecione...", value: "" },
  { label: "Sim", value: "yes" },
  { label: "Não", value: "no" },
];

export const pesiManifest: CalculatorManifest = {
  slug: "pesi",
  title: "PESI / sPESI",
  shortTitle: "PESI",
  description: "Estratificação prognóstica no tromboembolismo pulmonar.",
  seoTitle: "PESI / sPESI | Dosefy",
  seoDescription: "Calcule PESI completo e sPESI com interpretação clínica para risco em TEP.",
  heroEyebrow: "Tromboembolismo pulmonar",
  heroDescription:
    "Duas versões do escore em uma única interface: o sPESI para triagem simplificada e o PESI completo para classificação prognóstica mais detalhada.",
  heroHighlights: [
    "Alterna entre PESI completo e sPESI por abas no topo do formulário.",
    "Mostra score final, classe e leitura prática de risco.",
    "Mantém alerta de que decisão ambulatorial depende de estabilidade e contexto clínico.",
  ],
  resultMetricLabel: "PESI",
  actionLabel: "Calcular PESI",
  note: "Ferramenta de apoio à decisão. Não substitui julgamento clínico. A decisão de manejo ambulatorial exige estabilidade hemodinâmica, contexto social adequado e integração com imagem e biomarcadores.",
  limitations: [
    "Não substitui avaliação global do TEP, incluindo troponina, BNP, imagem e sinais de disfunção de ventrículo direito.",
    "Baixo risco pelo escore não significa alta automática.",
    "Instabilidade hemodinâmica ou hipoxemia significativa exigem manejo mais intensivo independentemente da classe.",
  ],
  references: [
    {
      label: "Aujesky et al. Outpatient versus inpatient treatment for patients with acute pulmonary embolism",
      href: "https://pubmed.ncbi.nlm.nih.gov/17470862/",
    },
    {
      label: "Jimenez et al. Simplification of the Pulmonary Embolism Severity Index",
      href: "https://pubmed.ncbi.nlm.nih.gov/20038755/",
    },
  ],
  variantTabs: {
    fieldName: "modelType",
    options: [
      {
        label: "PESI completo",
        value: "pesi",
        description: "Modelo detalhado com classe prognóstica I a V.",
      },
      {
        label: "sPESI",
        value: "spesi",
        description: "Versão simplificada para baixo risco versus maior risco.",
      },
    ],
  },
  sections: [
    {
      id: "common",
      title: "Parâmetros comuns",
      description: "Campos usados pelas duas versões do escore.",
    },
    {
      id: "pesi",
      title: "Variáveis do PESI completo",
      description: "Campos adicionais exigidos apenas no modelo completo.",
    },
    {
      id: "spesi",
      title: "Variáveis do sPESI",
      description: "Critérios adicionais da versão simplificada.",
    },
  ],
  fields: [
    {
      name: "age",
      label: "Idade",
      type: "number",
      sectionId: "common",
      inputMode: "numeric",
      placeholder: "Ex.: 54",
      min: 18,
      max: 120,
      suffix: "anos",
    },
    {
      name: "heartRate",
      label: "Frequência cardíaca",
      type: "number",
      sectionId: "common",
      inputMode: "numeric",
      placeholder: "Ex.: 112",
      min: 20,
      max: 250,
      suffix: "bpm",
    },
    {
      name: "systolicBloodPressure",
      label: "Pressão sistólica",
      type: "number",
      sectionId: "common",
      inputMode: "numeric",
      placeholder: "Ex.: 98",
      min: 30,
      max: 300,
      suffix: "mmHg",
    },
    {
      name: "oxygenSaturation",
      label: "SatO2",
      type: "number",
      sectionId: "common",
      inputMode: "numeric",
      placeholder: "Ex.: 89",
      min: 30,
      max: 100,
      suffix: "%",
    },
    {
      name: "sex",
      label: "Sexo biológico",
      type: "select",
      sectionId: "pesi",
      options: [
        { label: "Selecione...", value: "" },
        { label: "Masculino", value: "male" },
        { label: "Feminino", value: "female" },
      ],
      visibility: [{ field: "modelType", equals: "pesi" }],
    },
    {
      name: "cancer",
      label: "Câncer",
      type: "select",
      sectionId: "pesi",
      options: yesNoOptions,
      visibility: [{ field: "modelType", equals: "pesi" }],
    },
    {
      name: "heartFailure",
      label: "Insuficiência cardíaca",
      type: "select",
      sectionId: "pesi",
      options: yesNoOptions,
      visibility: [{ field: "modelType", equals: "pesi" }],
    },
    {
      name: "chronicLungDisease",
      label: "Doença pulmonar crônica",
      type: "select",
      sectionId: "pesi",
      options: yesNoOptions,
      visibility: [{ field: "modelType", equals: "pesi" }],
    },
    {
      name: "respiratoryRate",
      label: "Frequência respiratória",
      type: "number",
      sectionId: "pesi",
      inputMode: "numeric",
      placeholder: "Ex.: 32",
      min: 0,
      max: 80,
      suffix: "irpm",
      visibility: [{ field: "modelType", equals: "pesi" }],
    },
    {
      name: "temperature",
      label: "Temperatura",
      type: "number",
      sectionId: "pesi",
      inputMode: "decimal",
      placeholder: "Ex.: 35.8",
      min: 25,
      max: 45,
      step: 0.1,
      suffix: "°C",
      visibility: [{ field: "modelType", equals: "pesi" }],
    },
    {
      name: "alteredMentalStatus",
      label: "Alteração mental",
      type: "select",
      sectionId: "pesi",
      options: yesNoOptions,
      visibility: [{ field: "modelType", equals: "pesi" }],
    },
    {
      name: "activeCancer",
      label: "Câncer ativo",
      type: "select",
      sectionId: "spesi",
      options: yesNoOptions,
      visibility: [{ field: "modelType", equals: "spesi" }],
    },
    {
      name: "chronicCardiopulmonaryDisease",
      label: "Doença cardiopulmonar crônica",
      type: "select",
      sectionId: "spesi",
      options: yesNoOptions,
      visibility: [{ field: "modelType", equals: "spesi" }],
    },
  ],
  initialValues: {
    modelType: "pesi",
    age: "",
    heartRate: "",
    systolicBloodPressure: "",
    oxygenSaturation: "",
    sex: "",
    cancer: "",
    heartFailure: "",
    chronicLungDisease: "",
    respiratoryRate: "",
    temperature: "",
    alteredMentalStatus: "",
    activeCancer: "",
    chronicCardiopulmonaryDisease: "",
  },
};

export const calculatorManifest = pesiManifest;
